RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
AUTO_SHIFT_ENABLE = no
CONSOLE_ENABLE = no
CAPS_WORD_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes
OS_DETECTION_ENABLE = yes

TAP_DANCE_ENABLE = no
KEY_OVERRIDE_ENABLE = no
